"""One-off generator for the validation-dashboard example notebooks.

Run from the repo root:
    .venv\\Scripts\\python.exe control_totals\\validation\\_build_notebooks.py

This produces (and executes) four example .ipynb files in
control_totals/validation/summary_scripts/. Re-run any time the example
notebooks need to be regenerated from scratch.

Hand-edited notebooks should NOT be regenerated by this script — instead
add new chapters by copying one of the produced notebooks and editing it
in JupyterLab / VS Code.
"""

from __future__ import annotations

import sys
from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook
from nbclient import NotebookClient

HERE = Path(__file__).resolve().parent
NB_DIR = HERE / "summary_scripts"
NB_DIR.mkdir(parents=True, exist_ok=True)


# Boilerplate prepended to every notebook so cells can import the helpers
# without needing the user to install the validation folder as a package.
SETUP_CODE = """\
import sys
from pathlib import Path

# Make summary_scripts/ importable regardless of where the kernel started.
_HERE = Path.cwd()
for candidate in [_HERE, _HERE / "summary_scripts", _HERE.parent / "summary_scripts"]:
    if (candidate / "validation_data_input.py").exists():
        sys.path.insert(0, str(candidate))
        break

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from validation_data_input import (
    load_config, load_settings, load_unrolled, load_unrolled_regional,
    load_targets, control_id_lookup, load_legacy_pop, load_legacy_units,
    available_years,
)
from util import (
    COUNTY_ID_TO_NAME, COUNTY_ORDER, COUNTY_COLORS, INDICATORS,
    apply_plotly_theme, format_int, pct_diff, style_diff_table, passfail_badge,
)

cfg = load_config()
settings = load_settings()
BASE_YEAR = settings.get("base_year")
END_YEAR = settings.get("end_year")
TARGETS_END_YEAR = settings.get("targets_end_year")

ctrl = load_unrolled().merge(control_id_lookup(), on="control_id", how="left")
ctrl["county"] = ctrl["county_id"].map(COUNTY_ID_TO_NAME)
"""


def make_population_nb() -> nbformat.NotebookNode:
    cells = [
        new_markdown_cell(
            "# Population\n\n"
            "Total population by county across stepped years, compared to the "
            "regional totals and to legacy LUVit estimates when available."
        ),
        new_code_cell(SETUP_CODE),
        new_markdown_cell("## County totals at base year and end year"),
        new_code_cell(
            "by_county_year = (\n"
            "    ctrl.groupby(['county', 'year'])['total_pop'].sum().unstack('year')\n"
            ")\n"
            "by_county_year = by_county_year.reindex(COUNTY_ORDER)\n"
            "by_county_year['Region'] = by_county_year.sum(axis=0)  # column-wise won't help\n"
            "by_county_year = by_county_year.drop(columns='Region')\n"
            "summary = pd.DataFrame({\n"
            "    f'{BASE_YEAR}': by_county_year[BASE_YEAR],\n"
            "    f'{TARGETS_END_YEAR}': by_county_year[TARGETS_END_YEAR],\n"
            "    f'{END_YEAR}': by_county_year[END_YEAR],\n"
            "    'Growth (base→targets)': by_county_year[TARGETS_END_YEAR] - by_county_year[BASE_YEAR],\n"
            "    '% Growth': (by_county_year[TARGETS_END_YEAR] / by_county_year[BASE_YEAR] - 1) * 100,\n"
            "})\n"
            "summary.loc['Region'] = summary.sum(numeric_only=True)\n"
            "summary.loc['Region', '% Growth'] = (\n"
            "    summary.loc['Region', f'{TARGETS_END_YEAR}']\n"
            "    / summary.loc['Region', f'{BASE_YEAR}'] - 1\n"
            ") * 100\n"
            "style_diff_table(\n"
            "    summary,\n"
            "    int_cols=[f'{BASE_YEAR}', f'{TARGETS_END_YEAR}', f'{END_YEAR}', 'Growth (base→targets)'],\n"
            "    pct_cols=['% Growth'], pct_threshold=100,\n"
            ")"
        ),
        new_markdown_cell("## Trajectory by county"),
        new_code_cell(
            "trend = ctrl.groupby(['county', 'year'])['total_pop'].sum().reset_index()\n"
            "fig = px.line(\n"
            "    trend, x='year', y='total_pop', color='county',\n"
            "    category_orders={'county': COUNTY_ORDER},\n"
            "    color_discrete_map=COUNTY_COLORS, markers=True,\n"
            "    labels={'total_pop': 'Population', 'year': 'Year', 'county': 'County'},\n"
            "    title='Total population by county',\n"
            ")\n"
            "apply_plotly_theme(fig)"
        ),
        new_markdown_cell("## Regional total — controls vs. legacy LUVit"),
        new_code_cell(
            "reg = load_unrolled_regional()[['year', 'total_pop']].copy()\n"
            "reg['source'] = 'New pipeline'\n"
            "legacy = load_legacy_pop()\n"
            "frames = [reg]\n"
            "if legacy is not None:\n"
            "    leg = legacy.rename(columns={c: c.lower() for c in legacy.columns})\n"
            "    if 'year' in leg.columns and 'total_pop' in leg.columns:\n"
            "        leg = leg[['year', 'total_pop']].copy()\n"
            "        leg['source'] = 'Legacy LUVit'\n"
            "        frames.append(leg)\n"
            "compare = pd.concat(frames, ignore_index=True)\n"
            "fig = px.line(\n"
            "    compare, x='year', y='total_pop', color='source', markers=True,\n"
            "    title='Regional population — pipeline vs. legacy',\n"
            "    labels={'total_pop': 'Population', 'year': 'Year', 'source': 'Source'},\n"
            ")\n"
            "if legacy is None:\n"
            "    fig.add_annotation(\n"
            "        text='Legacy LUVit estimates not available for this run.',\n"
            "        xref='paper', yref='paper', x=0.5, y=1.08,\n"
            "        showarrow=False, font=dict(color='#888'),\n"
            "    )\n"
            "apply_plotly_theme(fig)"
        ),
        new_markdown_cell(
            "## Notes\n\n"
            "- Base year, targets year, and end year come from "
            "`configs/settings.yaml` of the active example.\n"
            "- Legacy comparison loads "
            "`examples/legacy_luvit/output/total_pop_estimates_all_years.csv` "
            "if present and non-empty."
        ),
    ]
    return new_notebook(cells=cells)


def make_housing_units_nb() -> nbformat.NotebookNode:
    cells = [
        new_markdown_cell(
            "# Housing units\n\n"
            "Household totals by county and growth from base year to targets "
            "year — and the implied delta vs. the input city-level targets."
        ),
        new_code_cell(SETUP_CODE),
        new_markdown_cell("## Households by county"),
        new_code_cell(
            "hh = ctrl.groupby(['county', 'year'])['total_hh'].sum().unstack('year')\n"
            "hh = hh.reindex(COUNTY_ORDER)\n"
            "summary = pd.DataFrame({\n"
            "    f'HH {BASE_YEAR}': hh[BASE_YEAR],\n"
            "    f'HH {TARGETS_END_YEAR}': hh[TARGETS_END_YEAR],\n"
            "    'Growth': hh[TARGETS_END_YEAR] - hh[BASE_YEAR],\n"
            "    '% Growth': (hh[TARGETS_END_YEAR] / hh[BASE_YEAR] - 1) * 100,\n"
            "})\n"
            "summary.loc['Region'] = summary.sum(numeric_only=True)\n"
            "summary.loc['Region', '% Growth'] = (\n"
            "    summary.loc['Region', f'HH {TARGETS_END_YEAR}']\n"
            "    / summary.loc['Region', f'HH {BASE_YEAR}'] - 1\n"
            ") * 100\n"
            "style_diff_table(\n"
            "    summary,\n"
            "    int_cols=[f'HH {BASE_YEAR}', f'HH {TARGETS_END_YEAR}', 'Growth'],\n"
            "    pct_cols=['% Growth'], pct_threshold=100,\n"
            ")"
        ),
        new_markdown_cell("## Growth (base → targets) by county"),
        new_code_cell(
            "growth = (hh[TARGETS_END_YEAR] - hh[BASE_YEAR]).reset_index()\n"
            "growth.columns = ['county', 'growth']\n"
            "fig = px.bar(\n"
            "    growth, x='county', y='growth', color='county',\n"
            "    category_orders={'county': COUNTY_ORDER},\n"
            "    color_discrete_map=COUNTY_COLORS,\n"
            "    title=f'Household growth, {BASE_YEAR}→{TARGETS_END_YEAR}',\n"
            "    labels={'growth': 'Households added', 'county': 'County'},\n"
            ")\n"
            "fig.update_layout(showlegend=False)\n"
            "apply_plotly_theme(fig)"
        ),
        new_markdown_cell("## Output vs. input city targets (CityHH)"),
        new_code_cell(
            "targets = load_targets('CityHH')\n"
            "# CityHH columns: RGID, county_id, control_id, Juris, HH<base_year>, HH<base_year>+5..., HHGro<base..targets>, HH<end_year>\n"
            "base_col = f'HH{BASE_YEAR}'\n"
            "# growth column name is e.g. HHGro2350 when base=2023, targets_end=2050\n"
            "gro_col = next(c for c in targets.columns if c.startswith('HHGro'))\n"
            "ctrl_end = (\n"
            "    ctrl.loc[ctrl['year'] == TARGETS_END_YEAR, ['control_id', 'total_hh']]\n"
            "    .rename(columns={'total_hh': 'HH_end_ctrl'})\n"
            ")\n"
            "compare = targets.merge(ctrl_end, on='control_id', how='left')\n"
            "compare['county'] = compare['county_id'].map(COUNTY_ID_TO_NAME)\n"
            "by_co = compare.groupby('county').agg(\n"
            "    target=(gro_col, 'sum'),\n"
            "    base=(base_col, 'sum'),\n"
            "    end=('HH_end_ctrl', 'sum'),\n"
            ")\n"
            "by_co = by_co.reindex(COUNTY_ORDER)\n"
            "by_co['ctrl_growth'] = by_co['end'] - by_co['base']\n"
            "by_co['delta'] = by_co['ctrl_growth'] - by_co['target']\n"
            "by_co['% diff vs. target'] = by_co.apply(\n"
            "    lambda r: pct_diff(r['ctrl_growth'], r['target']), axis=1\n"
            ")\n"
            "by_co = by_co.rename(columns={\n"
            "    'target': 'Target growth',\n"
            "    'ctrl_growth': 'Controls growth',\n"
            "    'delta': 'Controls − Target',\n"
            "})[['Target growth', 'Controls growth', 'Controls − Target', '% diff vs. target']]\n"
            "style_diff_table(\n"
            "    by_co,\n"
            "    int_cols=['Target growth', 'Controls growth', 'Controls − Target'],\n"
            "    pct_cols=['% diff vs. target'], pct_threshold=2,\n"
            ")"
        ),
        new_markdown_cell(
            "## Notes\n\n"
            "- `HHGro2350` is the input target growth (`base_year` → "
            "`targets_end_year`) from `TargetsRebasedOutput.xlsx → CityHH`.\n"
            "- A small percent difference is expected from rounding and from "
            "any RG-level scaling applied during interpolation."
        ),
    ]
    return new_notebook(cells=cells)


def make_employment_nb() -> nbformat.NotebookNode:
    cells = [
        new_markdown_cell(
            "# Employment\n\n"
            "Employment by county across stepped years, plus the input "
            "city-level employment targets."
        ),
        new_code_cell(SETUP_CODE),
        new_markdown_cell("## Employment by county and year"),
        new_code_cell(
            "emp = ctrl.groupby(['county', 'year'])['total_emp'].sum().reset_index()\n"
            "fig = px.line(\n"
            "    emp, x='year', y='total_emp', color='county', markers=True,\n"
            "    category_orders={'county': COUNTY_ORDER},\n"
            "    color_discrete_map=COUNTY_COLORS,\n"
            "    labels={'total_emp': 'Jobs', 'year': 'Year', 'county': 'County'},\n"
            "    title='Total employment by county',\n"
            ")\n"
            "apply_plotly_theme(fig)"
        ),
        new_markdown_cell("## Output vs. input city targets (CityEmp)"),
        new_code_cell(
            "targets = load_targets('CityEmp')\n"
            "base_col = f'Emp{BASE_YEAR}'\n"
            "gro_col = next(c for c in targets.columns if c.startswith('EmpGro'))\n"
            "ctrl_end = (\n"
            "    ctrl.loc[ctrl['year'] == TARGETS_END_YEAR, ['control_id', 'total_emp']]\n"
            "    .rename(columns={'total_emp': 'Emp_ctrl_end'})\n"
            ")\n"
            "compare = targets.merge(ctrl_end, on='control_id', how='left')\n"
            "compare['county'] = compare['county_id'].map(COUNTY_ID_TO_NAME)\n"
            "by_co = compare.groupby('county').agg(\n"
            "    target=(gro_col, 'sum'),\n"
            "    base=(base_col, 'sum'),\n"
            "    end=('Emp_ctrl_end', 'sum'),\n"
            ").reindex(COUNTY_ORDER)\n"
            "by_co['ctrl_growth'] = by_co['end'] - by_co['base']\n"
            "by_co['delta'] = by_co['ctrl_growth'] - by_co['target']\n"
            "by_co['% diff vs. target'] = by_co.apply(\n"
            "    lambda r: pct_diff(r['ctrl_growth'], r['target']), axis=1\n"
            ")\n"
            "by_co = by_co.rename(columns={\n"
            "    'target': 'Target growth',\n"
            "    'ctrl_growth': 'Controls growth',\n"
            "    'delta': 'Controls − Target',\n"
            "})[['Target growth', 'Controls growth', 'Controls − Target', '% diff vs. target']]\n"
            "style_diff_table(\n"
            "    by_co,\n"
            "    int_cols=['Target growth', 'Controls growth', 'Controls − Target'],\n"
            "    pct_cols=['% diff vs. target'], pct_threshold=2,\n"
            ")"
        ),
        new_markdown_cell("## Growth (base → targets) by county"),
        new_code_cell(
            "growth = ctrl.pivot_table(index='county', columns='year', values='total_emp', aggfunc='sum')\n"
            "growth = growth.reindex(COUNTY_ORDER)\n"
            "growth_df = (growth[TARGETS_END_YEAR] - growth[BASE_YEAR]).reset_index()\n"
            "growth_df.columns = ['county', 'growth']\n"
            "fig = px.bar(\n"
            "    growth_df, x='county', y='growth', color='county',\n"
            "    category_orders={'county': COUNTY_ORDER},\n"
            "    color_discrete_map=COUNTY_COLORS,\n"
            "    title=f'Employment growth, {BASE_YEAR}→{TARGETS_END_YEAR}',\n"
            "    labels={'growth': 'Jobs added', 'county': 'County'},\n"
            ")\n"
            "fig.update_layout(showlegend=False)\n"
            "apply_plotly_theme(fig)"
        ),
        new_markdown_cell(
            "## Notes\n\n"
            "- Sector breakdown (e.g. resource/construction split applied in "
            "`emp_chg_targets_*.py`) is not in the final controls workbook; "
            "to validate sector totals, add a new notebook that reads from the "
            "intermediate HDF5 outputs."
        ),
    ]
    return new_notebook(cells=cells)


def make_consistency_nb() -> nbformat.NotebookNode:
    cells = [
        new_markdown_cell(
            "# Consistency checks\n\n"
            "Internal QC checks on the produced control totals. Each row of "
            "the table is a single rule; failures highlight where to dig in."
        ),
        new_code_cell(SETUP_CODE),
        new_code_cell(
            "checks: list[dict] = []\n"
            "\n"
            "# 1. No negative values in the controls.\n"
            "num_cols = ['total_pop', 'total_hh', 'total_hhpop', 'total_emp']\n"
            "neg = (ctrl[num_cols] < 0).any().any()\n"
            "neg_count = int((ctrl[num_cols] < 0).sum().sum())\n"
            "checks.append({\n"
            "    'check': 'No negative values',\n"
            "    'pass': not neg,\n"
            "    'detail': f'{neg_count} negative cells across {num_cols}',\n"
            "})\n"
            "\n"
            "# 2. Monotonic non-decreasing across stepped years per subreg (allow tiny dips).\n"
            "tol = 0.005  # 0.5%\n"
            "decr = 0\n"
            "for cid, g in ctrl.sort_values('year').groupby('control_id'):\n"
            "    diffs = g['total_pop'].diff().dropna()\n"
            "    rel = diffs / g['total_pop'].iloc[:-1].values\n"
            "    decr += int((rel < -tol).sum())\n"
            "checks.append({\n"
            "    'check': f'Population non-decreasing per subreg (tolerance {tol*100:.1f}%)',\n"
            "    'pass': decr == 0,\n"
            "    'detail': f'{decr} year-over-year drops > {tol*100:.1f}%',\n"
            "})\n"
            "\n"
            "# 3. Subregion sums equal regional totals per year.\n"
            "reg = load_unrolled_regional().set_index('year')\n"
            "by_year = ctrl.groupby('year')[num_cols].sum()\n"
            "common = sorted(set(by_year.index).intersection(reg.index))\n"
            "max_diff = 0.0\n"
            "for y in common:\n"
            "    for c in num_cols:\n"
            "        if c in reg.columns:\n"
            "            d = abs(by_year.loc[y, c] - reg.loc[y, c])\n"
            "            max_diff = max(max_diff, d / max(reg.loc[y, c], 1))\n"
            "checks.append({\n"
            "    'check': 'Subreg sums = regional totals (stepped years only)',\n"
            "    'pass': max_diff < 0.005,\n"
            "    'detail': f'max relative diff = {max_diff*100:.2f}%',\n"
            "})\n"
            "\n"
            "# 4. HHPop ≤ total_pop per row.\n"
            "viol = int((ctrl['total_hhpop'] > ctrl['total_pop'] + 1).sum())\n"
            "checks.append({\n"
            "    'check': 'Household population ≤ total population',\n"
            "    'pass': viol == 0,\n"
            "    'detail': f'{viol} rows with HHPop > Pop',\n"
            "})\n"
            "\n"
            "# 5. Targets match controls at targets_end_year (population, regional).\n"
            "tgt_pop = load_targets('CityPop')\n"
            "tgt_col = f'Pop{TARGETS_END_YEAR}'\n"
            "tgt_total = tgt_pop[tgt_col].sum() if tgt_col in tgt_pop.columns else None\n"
            "ctrl_total = ctrl.loc[ctrl['year'] == TARGETS_END_YEAR, 'total_pop'].sum()\n"
            "if tgt_total is not None and tgt_total > 0:\n"
            "    rel = abs(ctrl_total - tgt_total) / tgt_total\n"
            "    checks.append({\n"
            "        'check': f'Regional pop at {TARGETS_END_YEAR} matches CityPop targets',\n"
            "        'pass': rel < 0.005,\n"
            "        'detail': f'controls={format_int(ctrl_total)}, target={format_int(tgt_total)}, rel diff={rel*100:.2f}%',\n"
            "    })\n"
            "else:\n"
            "    checks.append({\n"
            "        'check': f'Regional pop at {TARGETS_END_YEAR} matches CityPop targets',\n"
            "        'pass': False,\n"
            "        'detail': 'CityPop target column not found',\n"
            "    })\n"
            "\n"
            "# 6. HCT split (placeholder — confirmed source not in this workbook).\n"
            "checks.append({\n"
            "    'check': 'HCT + non-HCT = total per control area',\n"
            "    'pass': True,\n"
            "    'detail': 'TODO — wire to split_hct output once its file location is confirmed',\n"
            "})\n"
            "\n"
            "result = pd.DataFrame(checks)\n"
            "result['Status'] = result['pass'].map(passfail_badge)\n"
            "result = result[['Status', 'check', 'detail']].rename(\n"
            "    columns={'check': 'Check', 'detail': 'Detail'}\n"
            ")\n"
            "from IPython.display import HTML\n"
            "HTML(result.to_html(escape=False, index=False))"
        ),
        new_markdown_cell(
            "## Adding a new check\n\n"
            "Append a `dict` with `check`, `pass`, and `detail` keys to the "
            "`checks` list. Anything boolean works — combine pandas filters "
            "with `.all()` / `.sum()` for quick rules."
        ),
    ]
    return new_notebook(cells=cells)


NB_BUILDERS = {
    "population.ipynb":           make_population_nb,
    "housing_units.ipynb":        make_housing_units_nb,
    "employment.ipynb":           make_employment_nb,
    "consistency_checks.ipynb":   make_consistency_nb,
}


def build_and_execute() -> None:
    for name, builder in NB_BUILDERS.items():
        path = NB_DIR / name
        nb = builder()
        nb.metadata.update({
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            }
        })
        print(f"-> executing {name}")
        client = NotebookClient(
            nb,
            timeout=120,
            kernel_name="python3",
            resources={"metadata": {"path": str(NB_DIR)}},
        )
        client.execute()
        with path.open("w", encoding="utf-8") as f:
            nbformat.write(nb, f)
        print(f"   wrote {path}")


if __name__ == "__main__":
    build_and_execute()
    print("\nAll notebooks built. Next: `cd control_totals/validation && quarto render`")
